//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifestyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyRation
    {
        public int DailyRationId { get; set; }
        public int UserId { get; set; }
        public int RecepeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Calories { get; set; }
        public Nullable<double> Squirrels { get; set; }
        public Nullable<double> Fats { get; set; }
        public Nullable<double> Carbohydrates { get; set; }
        public Nullable<double> CaloriesUsers { get; set; }
        public Nullable<int> MealId { get; set; }
    }
}
