//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifestyle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activities> Activities { get; set; }
        public virtual DbSet<DailyRation> DailyRation { get; set; }
        public virtual DbSet<Diets> Diets { get; set; }
        public virtual DbSet<Difficulties> Difficulties { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Goals> Goals { get; set; }
        public virtual DbSet<IngredientForRecipe> IngredientForRecipe { get; set; }
        public virtual DbSet<Ingredients> Ingredients { get; set; }
        public virtual DbSet<Kitchens> Kitchens { get; set; }
        public virtual DbSet<Meals> Meals { get; set; }
        public virtual DbSet<Preparations> Preparations { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<RecipeTypes> RecipeTypes { get; set; }
        public virtual DbSet<Specifics> Specifics { get; set; }
        public virtual DbSet<Steps> Steps { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnitsOfMeasurement> UnitsOfMeasurement { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
