//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifestyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipes()
        {
            this.DailyRation = new HashSet<DailyRation>();
            this.IngredientForRecipe = new HashSet<IngredientForRecipe>();
            this.Steps = new HashSet<Steps>();
        }
    
        public int RecipeId { get; set; }
        public string Title { get; set; }
        public int MinutesOfCooking { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public string Photo { get; set; }
        public Nullable<int> MealId { get; set; }
        public Nullable<int> RecipeType { get; set; }
        public Nullable<int> DietId { get; set; }
        public Nullable<int> SpecificsId { get; set; }
        public Nullable<int> DifficultyId { get; set; }
        public Nullable<int> CookingId { get; set; }
        public Nullable<int> KitchenId { get; set; }
        public Nullable<int> Calories { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyRation> DailyRation { get; set; }
        public virtual Diets Diets { get; set; }
        public virtual Difficulties Difficulties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientForRecipe> IngredientForRecipe { get; set; }
        public virtual Kitchens Kitchens { get; set; }
        public virtual Meals Meals { get; set; }
        public virtual Preparations Preparations { get; set; }
        public virtual RecipeTypes RecipeTypes { get; set; }
        public virtual Specifics Specifics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Steps> Steps { get; set; }
    }
}
