//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyLifestyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Steps
    {
        public int StepId { get; set; }
        public int RecipeId { get; set; }
        public int StepNomen { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public string PhotoAnd { get; set; }
    
        public virtual Recipes Recipes { get; set; }
    }
}
